version: "3.8"
services:
    node-app:
        container_name: api_container
        restart: unless-stopped
        environment:
            - NODE_ENV=production
            - PORT=4000
        build:
            context: ./api
            dockerfile: Dockerfile
        # ports:
        #     - 4000:4000
        volumes:
            - ./api:/app
            - /app/node_modules
    react-app:
        build: ./web
        container_name: web_container
        # ports:
        #     - "5173:5173"
        stdin_open: true
        tty: true
        volumes:
            - ./web:/app
            - /app/node_modules
        depends_on:
            - node-app
    caddy:
        image: caddy/caddy:2.2.1-alpine
        container_name: caddy_container
        restart: unless-stopped
        ports:
            - 443:443
            - 80:80
        volumes:
            - $PWD/Caddyfile:/etc/caddy/Caddyfile
            - $PWD/site:/services
            - caddy_data:/data
            - caddy_config:/config
volumes:
    caddy_data:
        # external: true
    caddy_config:
