version: "3.8"

services:
    node-app:
        container_name: node-app
        restart: unless-stopped
        env_file: ./api/.env
        environment:
            - PORT=5000
        build:
            context: ./api
            dockerfile: Dockerfile
            tags:
                - node-app:latest
        networks:
            - backend

    react-app:
        build: ./web
        container_name: react-app
        networks:
            - frontend
            - backend
        depends_on:
            - node-app

    caddy:
        image: caddy/caddy:2.2.1-alpine
        container_name: caddy-service
        restart: unless-stopped
        ports:
            - 443:443
            - 80:80
        volumes:
            - $PWD/Caddyfile:/etc/caddy/Caddyfile
            - $PWD/site:/services
            - $PWD/web/dist:/var/www/html
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - frontend
            - backend
        depends_on:
            - node-app
            - react-app

volumes:
    caddy_data:
    caddy_config:

networks:
    frontend:
    backend:
